name: Spork
version: 0.19
abstract: Slide Presentations (Only Really Kwiki)
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.37
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
