name: Spork
version: 0.14
abstract: Slide Presentations (Only Really Kwiki)
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  IO::All: 0.16
  Spiffy: 0.15
  Spoon: 0.12
  Template: 2.00
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
